---
title: "CODEBOOK.md"
author: "Hasintha Attanayake"
date: "26 July 2015"
output: html_document
---

##CODEBOOK 
#Definition of Variables in tidydata set 'tidydata.txt'

63 variables in total:

"subject" <- participant in study. Factor variable from 1-30
"activity" <- specific activity subject performed

For the following 61 varialbes:
-'t' refers time domain signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz using a linear transform operations.
-'f' refers to a fourier transform operation.
-'BodyAcc' & 'GravityAcc' refer to body and acceleration components of gravity
-'BodyAccJerk' & 'BodyGyroJerk' refers to body liner acceration and body angularvelocity.
-'Mag' (as in tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag) refers to magnitude of a 3d signal via euclidan norm
- 'XYZ'/'X'/'Y'/'Z' refers to spatial measurment. 
-'.mean' refers to mean
-.std' refers to standard deviation
nb: for the following tidy data set each varaible is the average for each subject/activity factor level. 

"tBodyAcc.mean...X" 
"tBodyAcc.mean...Y" 
"tBodyAcc.mean...Z" 
"tGravityAcc.mean...X"
"tGravityAcc.mean...Y"
"tGravityAcc.mean...Z" 
"tBodyAccJerk.mean...X" 
"tBodyAccJerk.mean...Y"
"tBodyAccJerk.mean...Z" 
"tBodyGyro.mean...X" 
"tBodyGyro.mean...Y" 
"tBodyGyro.mean...Z" 
"tBodyGyroJerk.mean...X" 
"tBodyGyroJerk.mean...Y" 
"tBodyGyroJerk.mean...Z" 
"tBodyAccMag.mean.." 
"tGravityAccMag.mean.."
"tBodyAccJerkMag.mean.." 
"tBodyGyroMag.mean.." 
"tBodyGyroJerkMag.mean.." 
"fBodyAcc.mean...X" 
"fBodyAcc.mean...Y"
"fBodyAcc.mean...Z" 
"fBodyAccJerk.mean...X" 
"fBodyAccJerk.mean...Y" 
"fBodyAccJerk.mean...Z" 
"fBodyGyro.mean...X" 
"fBodyGyro.mean...Y" 
"fBodyGyro.mean...Z"
"fBodyAccMag.mean.."
"fBodyBodyAccJerkMag.mean.."
"fBodyBodyGyroMag.mean.."
"fBodyBodyGyroJerkMag.mean.."
"tBodyAcc.std...X" 
"tBodyAcc.std...Y" 
"tBodyAcc.std...Z"
"tGravityAcc.std...X"
"tGravityAcc.std...Y" 
"tGravityAcc.std...Z"
"tBodyAccJerk.std...X"
"tBodyAccJerk.std...Y"
"tBodyAccJerk.std...Z" 
"tBodyGyro.std...X"
"tBodyGyro.std...Y" 
"tBodyGyro.std...Z"
"tBodyGyroJerk.std...X"
"tBodyGyroJerk.std...Y" 
"tBodyGyroJerk.std...Z" 
"tBodyAccMag.std.."
"tGravityAccMag.std.." 
"tBodyAccJerkMag.std.."
"tBodyGyroMag.std.."
"tBodyGyroJerkMag.std.."
"fBodyAcc.std...X" 
"fBodyAcc.std...Y" 
"fBodyAcc.std...Z" 
"fBodyAccJerk.std...X" 
"fBodyAccJerk.std...Y"
"fBodyAccJerk.std...Z" 
"fBodyGyro.std...X" 
"fBodyGyro.std...Y"
"fBodyGyro.std...Z" 
"fBodyAccMag.std.." 
"fBodyBodyAccJerkMag.std.."
"fBodyBodyGyroMag.std.." 
"fBodyBodyGyroJerkMag.std.."
